AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app

Globals:
    Function:
        Timeout: 10
        Runtime: python3.7


Resources:

    PullRequestStandardCheckFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: pr_standard.handler
            Environment:
                Variables:
                    GITHUB_TOKEN: 123456
            Events:
                HelloWorld:
                    Type: Api
                    Properties:
                        Path: /standard
                        Method: post

    CodeFreezerSlashFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: codefreezer.handler
            Environment:
                Variables:
                    GITHUB_TOKEN: 123456
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /codefreeze
                        Method: post

# Outputs:

#     HelloWorldApi:
#       Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#       Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

#     HelloWorldFunction:
#       Description: "Hello World Lambda Function ARN"
#       Value: !GetAtt HelloWorldFunction.Arn

#     HelloWorldFunctionIamRole:
#       Description: "Implicit IAM Role created for Hello World function"
#       Value: !GetAtt HelloWorldFunctionRole.Arn
