AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAM with PR validation collection
    1. Standard Check
    2. CodeFreeze w/ GitHub Check + Slack Command
    3. Quality Check w/ GitHub Check + CircleCI WebHook

Parameters:
    GitHubToken:
        Type: String
        Description: >
            Token used to update PR status and write comments (aka summaries).
            Token provided should have permissions for repo and write:discussion.

    GitHubUser:
        Type: String
        Description: >
            The username assigned for the GitHubToken user (e.g. guilatrova).
            It's used to double check when a summary should be whether edited or deleted.

Globals:
    Function:
        Timeout: 10
        Runtime: python3.7
        Environment:
            Variables:
                GITHUB_TOKEN: !Ref GitHubToken
                GITHUB_USER: !Ref GitHubUser

Resources:

    # Pull Request Standards
    PullRequestStandardCheckFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: PullRequest_StandardCheck
            Description: >
                Updates status and provides a detailed summary
                for any changes made to a GitHub PullRequest
                based on company guidelines.
            CodeUri: src/
            Handler: pr_standard.handler
            Events:
                Webhook:
                    Type: Api
                    Properties:
                        Path: /standard
                        Method: post

    # Code Freeze (Slack + Pull Request)
    CodeFreezerSlashFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: codefreezer.slack_handler
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    REPOS: guilatrova/Github-Lambda-Status-Checks
                    AUTHORIZED: Guilherme
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /codefreeze
                        Method: post

    PullRequestCodeFreezeCheckFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: codefreezer.gh_handler
            Policies: AmazonDynamoDBReadOnlyAccess
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /codefreeze-status
                        Method: post

    ConfigTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: "CodeFreezeConfig"
            PrimaryKey:
                Name: ConfigName
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5

    # Quality Reports (CI + Pull Request)
    CIReportsFunction:
        Type: AWS::Serverless::Function
        Description: >
            Function to be invoked by CircleCI after reports were uploaded to S3.
            This function reads those reports, saves to DynamoDB, and then
            IF a PR is open, provide a status validation for Coverage and Quality.
        Properties:
            CodeUri: src/
            Handler: quality_summary.ci_handler
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref QualityReportsTable
                - S3ReadPolicy:
                    BucketName: !Ref QualityReportsBucket
            Environment:
                Variables:
                    TABLE_NAME: !Ref QualityReportsTable
                    BUCKET_NAME: !Ref QualityReportsBucket
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /ci-results
                        Method: post

    PullRequestQualityCheckFunction:
        Type: AWS::Serverless::Function
        Description: >
            Function to be invoked by GitHub when a PR is updated.
            This function reads reports saved previously in DynamoDB, and then
            IF any report is available, provide a status validation for Coverage and Quality.
        Properties:
            CodeUri: src/
            Handler: codefreezer.gh_handler
            Policies:
                - DynamoDBReadPolicy:
                    TableName: !Ref QualityReportsTable
            Events:
                Api:
                    Type: Api
                    Properties:
                        Path: /quality-status
                        Method: post

    QualityReportsTable:
        Type: AWS::Serverless::SimpleTable
        Description: Table used to store processed reports, project and build info.
        Properties:
            TableName: QualityReports
            PrimaryKey:
                Name: commit_sha
                Type: String

    QualityReportsBucket:
        Type: AWS::S3::Bucket
        Description: Bucket used to store raw reports generated by CircleCI.
        Properties:
            BucketName: ci-quality-reports
