AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    SAM with PR validation collection
    1. Standard Check
    2. CodeFreeze w/ GitHub Check + Slack Command
    3. Quality Check w/ GitHub Check + CircleCI WebHook

Parameters:
    GitHubToken:
        Type: String
        Description: >
            Token used to update PR status and write comments (aka summaries).
            Token provided should have permissions for repo and write:discussion.

    GitHubUser:
        Type: String
        Description: >
            The username assigned for the GitHubToken user (e.g. guilatrova).
            It's used to double check when a summary should be whether edited or deleted.

    ReportsBucketName:
        Type: String
        Description: S3 bucket that will be used to store/read quality/coverage reports.

    StandardDocs:
        Type: String
        Default: ""
        Description: >
            Link to the standards document.
            It will be added to the Guidelines Report.

    LambdaSecret:
        Type: String
        Description: Secret used to secure webhooks by signing payloads sent to lambda functions in header.

Globals:
    Function:
        Timeout: 10
        Runtime: python3.6
        Environment:
            Variables:
                GITHUB_TOKEN: !Ref GitHubToken
                GITHUB_USER: !Ref GitHubUser
                LAMBDA_SECRET: !Ref LambdaSecret

Resources:

    # Pull Request Standards
    PullRequestStandardCheckFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: StandardCheck_PullRequest
            Description: >
                Updates status and provides a detailed summary
                for any changes made to a GitHub PullRequest
                based on company guidelines.
            CodeUri: src/
            Handler: pr_standard.handler
            Environment:
                Variables:
                    DOCS_STANDARD_LINK: !Ref StandardDocs
            Events:
                Webhook:
                    Type: Api
                    Properties:
                        Path: /standard
                        Method: post

    # Quality Reports (CI + Pull Request)
    CIReportsFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: QualityCheck_CI_Reports
            Description: >
                Function to be invoked by CircleCI after reports were uploaded to S3.
                This function reads those reports, saves to DynamoDB, and then
                IF a PR is open, provide a status validation for Coverage and Quality.
            CodeUri: src/
            Handler: quality_summary.ci_handler
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref QualityReportsTable
                - S3ReadPolicy:
                    BucketName: !Ref QualityReportsBucket
            Environment:
                Variables:
                    BUCKET_NAME: !Ref QualityReportsBucket
            Events:
                Webhook:
                    Type: Api
                    Properties:
                        Path: /ci-results
                        Method: post

    PullRequestQualityCheckFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: QualityCheck_PullRequest
            Description: >
                Updates status and provides a detailed summary
                for any changes made to a GitHub PullRequest (e.g. new commits added)
                regarding Coverage and Quality.
                This function reads reports saved previously in DynamoDB.
            CodeUri: src/
            Handler: quality_summary.gh_handler
            Policies:
                - DynamoDBReadPolicy:
                    TableName: !Ref QualityReportsTable
            Events:
                Webhook:
                    Type: Api
                    Properties:
                        Path: /quality-status
                        Method: post

    QualityReportsTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: QualityReports
            ProvisionedThroughput:
              ReadCapacityUnits: 5
              WriteCapacityUnits: 5
            PrimaryKey:
                Name: commit_sha
                Type: String

    QualityReportsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Ref ReportsBucketName
